# Generated by Django 3.2.2 on 2021-05-15 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computacao', '0003_maquina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquina',
            old_name='alfabetoEntrada',
            new_name='alfabeto',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='alfabetoMaquina',
        ),
        migrations.RemoveField(
            model_name='maquina',
            name='simboloBranco',
        ),
    ]
